### ISSUE TITLE
Segmentation fault (core dumped) error 

### ISSUE THREAD

**Issue by ayok01** [ayme01/yukimi_learning_for_misskey#35]

**Comment by ayok01** [comment]
@neruneru0419

**Comment by ayok01** [comment]
エラー情報
Segmentation fault (core dumped) 
これがすべて
なぜなら
エラーをキャッチする処理書き忘れてる

**Comment by ayok01** [comment]
エラーキャッチできた
```
                    misskey.io                                                  
           DEBUG    https://misskey.io:443 "POST           connectionpool.py:429
                    /api/notes/reactions/create HTTP/1.1"                       
                    429 260                                                     
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/git/yukimi_learning_for_misskey/src/Misskey/get_timeline.py", line 76, in get_tl_misskey
    if choice_note['reactions']['❤'] == 1:
KeyError: '❤'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main2.py", line 43, in cron_note
    text = get_tl_misskey()
  File "/root/git/yukimi_learning_for_misskey/src/Misskey/get_timeline.py", line 87, in get_tl_misskey
    misskey.notes_reactions_create(choice_id,"❤️")
  File "/usr/local/lib/python3.8/dist-packages/misskey/misskey.py", line 905, in notes_reactions_create
    return self.__request_api('notes/reactions/create', **params)
  File "/usr/local/lib/python3.8/dist-packages/misskey/misskey.py", line 156, in __request_api
    raise MisskeyAPIException(response.json())
misskey.exceptions.MisskeyAPIException: RATE_LIMIT_EXCEEDED(IO-HWMN2): Rate limit exceeded. Please try again later.

リクエストが多すぎます。
しばらく待ってから再度やり直してください。
[11:05:13] DEBUG    Resetting dropped connection:          connectionpool.py:267
                    misskey.io                      
```

**Comment by ayok01** [comment]
#36 のリファクタリングで修正してみた
いったん様子見

**Comment by ayok01** [comment]
だめだ…Pythonだと低レイヤーでなってそう原因特定難しい。
Goとかrustに書き換えようかな…
